config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  delete 'cocktails/:id/photo', to: 'cocktails#delete_photo', as: :delete_photo
  patch 'cocktails/:id', to: 'cocktails#update_photo', as: :update_photo
  resources :cocktails, only: [ :show, :new, :destroy, :create] do
    resources :doses, only: [ :new, :create ]
  end
  # delete 'cocktails/:id', to: 'cocktails#delete_photo', as: :delete_photo
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: [:ingredient, :cocktail] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
  default_scope { order(name: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy, :delete_photo, :update_photo]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path, method: :get
  end

   def delete_photo
    @cocktail.photo.purge
    redirect_to cocktail_path(@cocktail)
  end

  def update_photo
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :show
    end
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail_id = params[:cocktail_id]
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_image_field.html.erb
  <%= f.input :photo, hint: "jolie photo uniquement ;)", label:'Selectionner une photo', as: :file, input_html: { accept: "image/*" }%>

app/views/cocktails/index.html.erb
<div class="navbar-lewagon">
  <h1 class="display-4"><strong>Mister Cocktails !</strong></h1>
</div>
<div class="container">
 <div class="cards">
  <% @cocktails.each do |cocktail| %>
    <% if cocktail.photo.attached? %>
      <div class="card-category" style="background-image: url('<%= cl_image_path cocktail.photo.key, alt: cocktail.name, width: 400, height: 300, crop: :fill %>')">
        <%= link_to cocktail.name, cocktail_path(cocktail)%>
      </div>
    <% else %>
      <div class="card-category rand-image">
        <%= link_to cocktail.name, cocktail_path(cocktail)%>
      </div>
    <% end %>
  <% end %>
  <div class="card-category rand-image new-cocktail">
    <%= link_to 'new cocktail', new_cocktail_path %>
  </div>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="navbar-lewagon">
  <h1 class="display-5"><strong>Ajouter un nouveau cocktail !</strong></h1>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="form">
         <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name, label: 'Nom du cocktail', placeholder: 'Mojito..'%>
      <!-- </div> -->
      <!-- <div class="img-form"> -->
        <%= render partial: "image_field", :locals => {:f => f}, class: "img-form" %>
      <!-- </div> -->
      <!-- <div class="d-flex justify-content-between mt-3"> -->
          <%= f.button :submit, "Creer le cocktail", class: "flex-item btn-primary" %>
        <% end %>
        <%= button_to 'Annuler', root_path, method: :get, type: "button", class: "flex-item btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="navbar-lewagon">
  <h1 class="display-5"><%= @cocktail.name %></h1>
</div>
<div class="container mt-5">
  <div class="d-flex justify-content-between">
    <%= button_to 'Retour', root_path, method: :get, type: "button", class: "btn btn-outline-info" %>
    <%= button_to cocktail_path(@cocktail),
            method: :delete,
            data: { confirm: "Voulez-vous supprimer le cocktail ?" },
            type: "button",
            class: "btn btn-info" do %>
            Supprimer <br><%= @cocktail.name %>
          <% end %>
  </div>
  <div class="d-fex justify-content-between">
      <% if @cocktail.photo.attached? %>
            <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
            <%= link_to delete_photo_path(@cocktail),
            method: :delete,
            data: { confirm: "Delete this photo ?" } do %>
              <p>Delete this photo ? -> <i class="fas fa-trash-alt"></i></p>
            <% end %>
          <% else %>
            <%= simple_form_for(@cocktail, url: update_photo_path, method: 'patch') do |f| %>
            <%= render partial: "image_field", locals: {:f => f}, required: true %>
            <%= f.button :submit, "Ajouter la photo", class: "btn btn-success" %>
            <% end %>
          <% end %>
      <h3>list of ingredients : </h3>
          <ul>
            <% @cocktail.doses.each do |dose| %>
              <li><%= "#{dose.ingredient.name} - #{dose.description} - " %>
                <%= link_to dose_path(dose),
                  method: :delete,
                  data: { confirm: "supprimer l'ingredient ?" } do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </li>
            <% end %>
            <li><%= link_to 'add ingredients', new_cocktail_dose_path(@cocktail) %>
            </li>
          </ul>
  </div>
</div>

app/views/doses/new.html.erb
<h1>Add ingredients to your <%= @cocktail.name %> recipe</h1>

<%= simple_form_for [ @cocktail, @dose ], wrapper: :inline_form, html: { class: "form-inline" } do |f| %>
  <%= f.association :ingredient, input_html: { class: "mb-2 mr-sm-2" }%>
  <%= f.input :description, input_html: { class: "mb-2 mr-sm-2" }%>
  <%= f.button :submit, class: "btn-primary mb-2" %>
<% end %>
<%= button_to 'cancel', cocktail_path(@cocktail), method: :get, :type => "button", :class => "btn-outline-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barnabe's MisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>